select A.PRODUCT_ID,A.PRODUCT_NAME,A.CATEGORY,A.PRICE,A.STOCK 
from MYDB.SUPABASE_CASESTUDY_BANU_SNF_CASESTUDY_BANU.STG_PRODUCTS as A
UNION ALL
select B.PRODUCT_ID,B.PRODUCT_NAME,B.CATEGORY,B.PRICE,B.STOCK 
from MYDB.ONEDRIVE_SNF_CASE.PRODUCT_DATA_SHEET_1 as  B





 





