SELECT T.ID,T.FIRST_NAME,T.LAST_NAME,
CASE When T.PRODUCT_NAME = 'Cell Phone' THEN 'Mobiles' ELSE T.PRODUCT_NAME END AS PRODUCT_NAME,
T.ITEMS_SOLD, T.SOLD_PRICE, T.ITEMS_SOLD*T.SOLD_PRICE as TOTAL_SALES,
CASE When T.ITEMS_SOLD*T.SOLD_PRICE >= 3000 THEN 'HIGH' WHEN T.ITEMS_SOLD*T.SOLD_PRICE >= 1500 
THEN 'MEDIUM' ELSE 'LOW' END as Sales_Status,T.SOLD_DATE, T.COUNTRY, T.REGION
FROM MYDB.ONE_DRIVE.TOTAL_SALE_IN  AS T
INNER JOIN 
MYDB.SUPABASE_MYSCHEMA.SALESPERSONS  AS SP 
on T.ID=SP.SALEPERSONID
